import Foundation

struct SessionQuote: Equatable {
    let text: String
    let author: String
}

enum SessionGreetingLibrary {
    /// Short greetings spanning more than thirty languages. A value is chosen
    /// once per launch and intentionally displayed without a language label.
    static let all = [
        "Hello", "Hola", "Bonjour", "Ciao", "Hallo", "Olá", "Welkom",
        "こんにちは", "안녕하세요", "你好", "नमस्ते", "Привет", "مرحبًا", "שלום",
        "Γεια σου", "Cześć", "Ahoj", "Szia", "Hei", "Hej", "Halló", "Tere",
        "Sveiki", "Labas", "Здравей", "Bună", "Zdravo", "Merhaba", "Sawubona",
        "Jambo", "Kumusta", "Xin chào", "สวัสดี", "Selamat datang", "Halo",
        "Salam", "Kaixo", "Dia dhuit", "Helo", "Përshëndetje", "Barev",
        "Mingalaba", "Sannu", "Habari", "Talofa", "Bula"
    ]

    static func random() -> String {
        all.randomElement() ?? "Hello"
    }
}

enum SessionQuoteLibrary {
    // Short quotations from real historical figures, selected from the CC0
    // Quotables corpus: https://www.kaggle.com/datasets/alvations/quotables
    static let all: [SessionQuote] = [
        SessionQuote(text: "Hope is a waking dream.", author: "Aristotle"),
        SessionQuote(text: "The energy of the mind is the essence of life.", author: "Aristotle"),
        SessionQuote(text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle"),
        SessionQuote(text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle"),
        SessionQuote(text: "Happiness depends upon ourselves.", author: "Aristotle"),
        SessionQuote(text: "A friend to all is a friend to none.", author: "Aristotle"),
        SessionQuote(text: "Quality is not an act, it is a habit.", author: "Aristotle"),
        SessionQuote(text: "The direction in which education starts a man will determine his future in life.", author: "Plato"),
        SessionQuote(text: "The beginning is the most important part of the work.", author: "Plato"),
        SessionQuote(text: "No law or ordinance is mightier than understanding.", author: "Plato"),
        SessionQuote(text: "Opinion is the medium between knowledge and ignorance.", author: "Plato"),
        SessionQuote(text: "A good decision is based on knowledge and not on numbers.", author: "Plato"),
        SessionQuote(text: "Human behavior flows from three main sources: desire, emotion, and knowledge.", author: "Plato"),
        SessionQuote(text: "Love is the joy of the good, the wonder of the wise, the amazement of the Gods.", author: "Plato"),
        SessionQuote(text: "Wisdom begins in wonder.", author: "Socrates"),
        SessionQuote(text: "Beware the barrenness of a busy life.", author: "Socrates"),
        SessionQuote(text: "The unexamined life is not worth living.", author: "Socrates"),
        SessionQuote(text: "The only true wisdom is in knowing you know nothing.", author: "Socrates"),
        SessionQuote(text: "True knowledge exists in knowing that you know nothing.", author: "Socrates"),
        SessionQuote(text: "He is richest who is content with the least, for content is the wealth of nature.", author: "Socrates"),
        SessionQuote(text: "To know, is to know that you know nothing. That is the meaning of true knowledge.", author: "Socrates"),
        SessionQuote(text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", author: "Marcus Aurelius"),
        SessionQuote(text: "Confine yourself to the present.", author: "Marcus Aurelius"),
        SessionQuote(text: "Our life is what our thoughts make it.", author: "Marcus Aurelius"),
        SessionQuote(text: "Loss is nothing else but change, and change is Nature's delight.", author: "Marcus Aurelius"),
        SessionQuote(text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius"),
        SessionQuote(text: "You have power over your mind - not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius"),
        SessionQuote(text: "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.", author: "Marcus Aurelius"),
        SessionQuote(text: "We should not moor a ship with one anchor, or our life with one hope.", author: "Epictetus"),
        SessionQuote(text: "Neither should a ship rely on one small anchor, nor should life rest on a single hope.", author: "Epictetus"),
        SessionQuote(text: "Is freedom anything else than the right to live as we wish? Nothing else.", author: "Epictetus"),
        SessionQuote(text: "The two powers which in my opinion constitute a wise man are those of bearing and forbearing.", author: "Epictetus"),
        SessionQuote(text: "Only the educated are free.", author: "Epictetus"),
        SessionQuote(text: "If you wish to be a writer, write.", author: "Epictetus"),
        SessionQuote(text: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus"),
        SessionQuote(text: "You cannot open a book without learning something.", author: "Confucius"),
        SessionQuote(text: "Choose a job you love, and you will never have to work a day in your life.", author: "Confucius"),
        SessionQuote(text: "Wisdom, compassion, and courage are the three universally recognized moral qualities of men.", author: "Confucius"),
        SessionQuote(text: "He who learns but does not think, is lost! He who thinks but does not learn is in great danger.", author: "Confucius"),
        SessionQuote(text: "Silence is a true friend who never betrays.", author: "Confucius"),
        SessionQuote(text: "When anger rises, think of the consequences.", author: "Confucius"),
        SessionQuote(text: "Everything has beauty, but not everyone sees it.", author: "Confucius"),
        SessionQuote(text: "To the mind that is still, the whole universe surrenders.", author: "Lao Tzu"),
        SessionQuote(text: "Knowing others is wisdom, knowing yourself is Enlightenment.", author: "Lao Tzu"),
        SessionQuote(text: "If you do not change direction, you may end up where you are heading.", author: "Lao Tzu"),
        SessionQuote(text: "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.", author: "Lao Tzu"),
        SessionQuote(text: "I have just three things to teach: simplicity, patience, compassion. These three are your greatest treasures.", author: "Lao Tzu"),
        SessionQuote(text: "Kindness in words creates confidence. Kindness in thinking creates profoundness. Kindness in giving creates love.", author: "Lao Tzu"),
        SessionQuote(text: "Silence is a source of great strength.", author: "Lao Tzu"),
        SessionQuote(text: "One touch of nature makes the whole world kin.", author: "William Shakespeare"),
        SessionQuote(text: "A fool thinks himself to be wise, but a wise man knows himself to be a fool.", author: "William Shakespeare"),
        SessionQuote(text: "Love looks not with the eyes, but with the mind, And therefore is winged Cupid painted blind.", author: "William Shakespeare"),
        SessionQuote(text: "The wheel is come full circle.", author: "William Shakespeare"),
        SessionQuote(text: "Listen to many, speak to a few.", author: "William Shakespeare"),
        SessionQuote(text: "No legacy is so rich as honesty.", author: "William Shakespeare"),
        SessionQuote(text: "If music be the food of love, play on.", author: "William Shakespeare"),
        SessionQuote(text: "The only way to have a friend is to be one.", author: "Ralph Waldo Emerson"),
        SessionQuote(text: "It is not length of life, but depth of life.", author: "Ralph Waldo Emerson"),
        SessionQuote(text: "Nature always wears the colors of the spirit.", author: "Ralph Waldo Emerson"),
        SessionQuote(text: "Love of beauty is taste. The creation of beauty is art.", author: "Ralph Waldo Emerson"),
        SessionQuote(text: "All life is an experiment. The more experiments you make the better.", author: "Ralph Waldo Emerson"),
        SessionQuote(text: "For every minute you remain angry, you give up sixty seconds of peace of mind.", author: "Ralph Waldo Emerson"),
        SessionQuote(text: "Our greatest glory is not in never failing, but in rising up every time we fail.", author: "Ralph Waldo Emerson"),
        SessionQuote(text: "Wealth is the ability to fully experience life.", author: "Henry David Thoreau"),
        SessionQuote(text: "Not until we are lost do we begin to understand ourselves.", author: "Henry David Thoreau"),
        SessionQuote(text: "True friendship can afford true knowledge. It does not depend on darkness and ignorance.", author: "Henry David Thoreau"),
        SessionQuote(text: "Things do not change; we change.", author: "Henry David Thoreau"),
        SessionQuote(text: "This world is but a canvas to our imagination.", author: "Henry David Thoreau"),
        SessionQuote(text: "The language of friendship is not words but meanings.", author: "Henry David Thoreau"),
        SessionQuote(text: "The most I can do for my friend is simply be his friend.", author: "Henry David Thoreau"),
        SessionQuote(text: "Lost time is never found again.", author: "Benjamin Franklin"),
        SessionQuote(text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin"),
        SessionQuote(text: "Either write something worth reading or do something worth writing.", author: "Benjamin Franklin"),
        SessionQuote(text: "Early to bed and early to rise makes a man healthy, wealthy and wise.", author: "Benjamin Franklin"),
        SessionQuote(text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin"),
        SessionQuote(text: "A house is not a home unless it contains food and fire for the mind as well as the body.", author: "Benjamin Franklin"),
        SessionQuote(text: "The Constitution only gives people the right to pursue happiness. You have to catch it yourself.", author: "Benjamin Franklin"),
        SessionQuote(text: "The best thing about the future is that it comes one day at a time.", author: "Abraham Lincoln"),
        SessionQuote(text: "All that I am, or hope to be, I owe to my angel mother.", author: "Abraham Lincoln"),
        SessionQuote(text: "Most folks are as happy as they make up their minds to be.", author: "Abraham Lincoln"),
        SessionQuote(text: "In the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln"),
        SessionQuote(text: "Better to remain silent and be thought a fool than to speak out and remove all doubt.", author: "Abraham Lincoln"),
        SessionQuote(text: "Always bear in mind that your own resolution to succeed is more important than any other.", author: "Abraham Lincoln"),
        SessionQuote(text: "Nearly all men can stand adversity, but if you want to test a man's character, give him power.", author: "Abraham Lincoln"),
        SessionQuote(text: "Good friends, good books and a sleepy conscience: this is the ideal life.", author: "Mark Twain"),
        SessionQuote(text: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain"),
        SessionQuote(text: "To succeed in life, you need two things: ignorance and confidence.", author: "Mark Twain"),
        SessionQuote(text: "You can't depend on your eyes when your imagination is out of focus.", author: "Mark Twain"),
        SessionQuote(text: "Kindness is the language which the deaf can hear and the blind can see.", author: "Mark Twain"),
        SessionQuote(text: "Age is an issue of mind over matter. If you don't mind, it doesn't matter.", author: "Mark Twain"),
        SessionQuote(text: "My mother had a great deal of trouble with me, but I think she enjoyed it.", author: "Mark Twain"),
        SessionQuote(text: "Laughter is not at all a bad beginning for a friendship, and it is far the best ending for one.", author: "Oscar Wilde"),
        SessionQuote(text: "Experience is simply the name we give our mistakes.", author: "Oscar Wilde"),
        SessionQuote(text: "Memory... is the diary that we all carry about with us.", author: "Oscar Wilde"),
        SessionQuote(text: "If you are not too long, I will wait here for you all my life.", author: "Oscar Wilde"),
        SessionQuote(text: "Some cause happiness wherever they go; others whenever they go.", author: "Oscar Wilde"),
        SessionQuote(text: "I am so clever that sometimes I don't understand a single word of what I am saying.", author: "Oscar Wilde"),
        SessionQuote(text: "True friends stab you in the front.", author: "Oscar Wilde"),
        SessionQuote(text: "Life seems but a quick succession of busy nothings.", author: "Jane Austen"),
        SessionQuote(text: "Friendship is certainly the finest balm for the pangs of disappointed love.", author: "Jane Austen"),
        SessionQuote(text: "I have been a selfish being all my life, in practice, though not in principle.", author: "Jane Austen"),
        SessionQuote(text: "Selfishness must always be forgiven you know, because there is no hope of a cure.", author: "Jane Austen"),
        SessionQuote(text: "There is no charm equal to tenderness of heart.", author: "Jane Austen"),
        SessionQuote(text: "What is right to be done cannot be done too soon.", author: "Jane Austen"),
        SessionQuote(text: "There is nothing like staying at home for real comfort.", author: "Jane Austen"),
        SessionQuote(text: "The beginning of compunction is the beginning of a new life.", author: "George Eliot"),
        SessionQuote(text: "Life began with waking up and loving my mother's face.", author: "George Eliot"),
        SessionQuote(text: "Animals are such agreeable friends - they ask no questions; they pass no criticisms.", author: "George Eliot"),
        SessionQuote(text: "More helpful than all wisdom is one draught of simple human pity that will not forsake us.", author: "George Eliot"),
        SessionQuote(text: "Failure after long perseverance is much grander than never to have a striving good enough to be called a failure.", author: "George Eliot"),
        SessionQuote(text: "Consequences are unpitying.", author: "George Eliot"),
        SessionQuote(text: "Adventure is not outside man; it is within.", author: "George Eliot"),
        SessionQuote(text: "That best portion of a man's life, his little, nameless, unremembered acts of kindness and love.", author: "William Wordsworth"),
        SessionQuote(text: "The best portion of a good man's life is his little, nameless, unremembered acts of kindness and of love.", author: "William Wordsworth"),
        SessionQuote(text: "Nature never did betray the heart that loved her.", author: "William Wordsworth"),
        SessionQuote(text: "Wisdom is oftentimes nearer when we stoop than when we soar.", author: "William Wordsworth"),
        SessionQuote(text: "Come forth into the light of things, let nature be your teacher.", author: "William Wordsworth"),
        SessionQuote(text: "The child is father of the man.", author: "William Wordsworth"),
        SessionQuote(text: "Faith is a passionate intuition.", author: "William Wordsworth"),
        SessionQuote(text: "The love of learning, the sequestered nooks, And all the sweet serenity of books.", author: "Henry Wadsworth Longfellow"),
        SessionQuote(text: "In character, in manner, in style, in all things, the supreme excellence is simplicity.", author: "Henry Wadsworth Longfellow"),
        SessionQuote(text: "Simplicity in character, in manners, in style; in all things the supreme excellence is simplicity.", author: "Henry Wadsworth Longfellow"),
        SessionQuote(text: "A single conversation across the table with a wise man is better than ten years mere study of books.", author: "Henry Wadsworth Longfellow"),
        SessionQuote(text: "Into each life some rain must fall.", author: "Henry Wadsworth Longfellow"),
        SessionQuote(text: "It takes less time to do a thing right, than it does to explain why you did it wrong.", author: "Henry Wadsworth Longfellow"),
        SessionQuote(text: "Sit in reverie and watch the changing color of the waves that break upon the idle seashore of the mind.", author: "Henry Wadsworth Longfellow"),
        SessionQuote(text: "Is there anyone so wise as to learn by the experience of others?", author: "Voltaire"),
        SessionQuote(text: "Love is a canvas furnished by nature and embroidered by imagination.", author: "Voltaire"),
        SessionQuote(text: "Judge a man by his questions rather than his answers.", author: "Voltaire"),
        SessionQuote(text: "The art of medicine consists in amusing the patient while nature cures the disease.", author: "Voltaire"),
        SessionQuote(text: "Common sense is not so common.", author: "Voltaire"),
        SessionQuote(text: "Tears are the silent language of grief.", author: "Voltaire"),
        SessionQuote(text: "The superfluous, a very necessary thing.", author: "Voltaire"),
        SessionQuote(text: "Character develops itself in the stream of life.", author: "Johann Wolfgang von Goethe"),
        SessionQuote(text: "Ignorant men raise questions that wise men answered a thousand years ago.", author: "Johann Wolfgang von Goethe"),
        SessionQuote(text: "The soul that sees beauty may sometimes walk alone.", author: "Johann Wolfgang von Goethe"),
        SessionQuote(text: "Life belongs to the living, and he who lives must be prepared for changes.", author: "Johann Wolfgang von Goethe"),
        SessionQuote(text: "Beauty is a manifestation of secret natural laws, which otherwise would have been hidden from us forever.", author: "Johann Wolfgang von Goethe"),
        SessionQuote(text: "Nothing is worth more than this day.", author: "Johann Wolfgang von Goethe"),
        SessionQuote(text: "I love those who yearn for the impossible.", author: "Johann Wolfgang von Goethe"),
        SessionQuote(text: "Imagination disposes of everything; it creates beauty, justice, and happiness, which are everything in this world.", author: "Blaise Pascal"),
        SessionQuote(text: "Man's greatness lies in his power of thought.", author: "Blaise Pascal"),
        SessionQuote(text: "Do you wish people to think well of you? Don't speak well of yourself.", author: "Blaise Pascal"),
        SessionQuote(text: "Noble deeds that are concealed are most esteemed.", author: "Blaise Pascal"),
        SessionQuote(text: "Kind words do not cost much. Yet they accomplish much.", author: "Blaise Pascal"),
        SessionQuote(text: "The heart has its reasons of which reason knows nothing.", author: "Blaise Pascal"),
        SessionQuote(text: "Little things console us because little things afflict us.", author: "Blaise Pascal"),
        SessionQuote(text: "In order to improve the mind, we ought less to learn, than to contemplate.", author: "Rene Descartes"),
        SessionQuote(text: "The reading of all good books is like a conversation with the finest minds of past centuries.", author: "Rene Descartes"),
        SessionQuote(text: "I think; therefore I am.", author: "Rene Descartes"),
        SessionQuote(text: "It is not enough to have a good mind; the main thing is to use it well.", author: "Rene Descartes"),
        SessionQuote(text: "I am indeed amazed when I consider how weak my mind is and how prone to error.", author: "Rene Descartes"),
        SessionQuote(text: "I am accustomed to sleep and in my dreams to imagine the same things that lunatics imagine when awake.", author: "Rene Descartes"),
        SessionQuote(text: "Everything is self-evident.", author: "Rene Descartes"),
        SessionQuote(text: "Science is organized knowledge. Wisdom is organized life.", author: "Immanuel Kant"),
        SessionQuote(text: "Happiness is not an ideal of reason, but of imagination.", author: "Immanuel Kant"),
        SessionQuote(text: "It is beyond a doubt that all our knowledge begins with experience.", author: "Immanuel Kant"),
        SessionQuote(text: "I had therefore to remove knowledge, in order to make room for belief.", author: "Immanuel Kant"),
        SessionQuote(text: "Live your life as though your every act were to become a universal law.", author: "Immanuel Kant"),
        SessionQuote(text: "May you live your life as if the maxim of your actions were to become universal law.", author: "Immanuel Kant"),
        SessionQuote(text: "Experience without theory is blind, but theory without experience is mere intellectual play.", author: "Immanuel Kant"),
        SessionQuote(text: "Satisfaction consists in freedom from pain, which is the positive element of life.", author: "Arthur Schopenhauer"),
        SessionQuote(text: "The two enemies of human happiness are pain and boredom.", author: "Arthur Schopenhauer"),
        SessionQuote(text: "Just remember, once you're over the hill you begin to pick up speed.", author: "Arthur Schopenhauer"),
        SessionQuote(text: "To live alone is the fate of all great souls.", author: "Arthur Schopenhauer"),
        SessionQuote(text: "Great men are like eagles, and build their nest on some lofty solitude.", author: "Arthur Schopenhauer"),
        SessionQuote(text: "The more unintelligent a man is, the less mysterious existence seems to him.", author: "Arthur Schopenhauer"),
        SessionQuote(text: "Every man takes the limits of his own field of vision for the limits of the world.", author: "Arthur Schopenhauer"),
        SessionQuote(text: "Without music, life would be a mistake.", author: "Friedrich Nietzsche"),
        SessionQuote(text: "It is not a lack of love, but a lack of friendship that makes unhappy marriages.", author: "Friedrich Nietzsche"),
        SessionQuote(text: "Hope in reality is the worst of all evils because it prolongs the torments of man.", author: "Friedrich Nietzsche"),
        SessionQuote(text: "We love life, not because we are used to living but because we are used to loving.", author: "Friedrich Nietzsche"),
        SessionQuote(text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche"),
        SessionQuote(text: "When you look into an abyss, the abyss also looks into you.", author: "Friedrich Nietzsche"),
        SessionQuote(text: "To live is to suffer, to survive is to find some meaning in the suffering.", author: "Friedrich Nietzsche"),
        SessionQuote(text: "The two most powerful warriors are patience and time.", author: "Leo Tolstoy"),
        SessionQuote(text: "If you want to be happy, be.", author: "Leo Tolstoy"),
        SessionQuote(text: "True life is lived when tiny changes occur.", author: "Leo Tolstoy"),
        SessionQuote(text: "The sole meaning of life is to serve humanity.", author: "Leo Tolstoy"),
        SessionQuote(text: "Without knowing what I am and why I am here, life is impossible.", author: "Leo Tolstoy"),
        SessionQuote(text: "It is amazing how complete is the delusion that beauty is goodness.", author: "Leo Tolstoy"),
        SessionQuote(text: "All, everything that I understand, I understand only because I love.", author: "Leo Tolstoy"),
        SessionQuote(text: "To live without Hope is to Cease to live.", author: "Fyodor Dostoevsky"),
        SessionQuote(text: "The greatest happiness is to know the source of unhappiness.", author: "Fyodor Dostoevsky"),
        SessionQuote(text: "Happiness does not lie in happiness, but in the achievement of it.", author: "Fyodor Dostoevsky"),
        SessionQuote(text: "The soul is healed by being with children.", author: "Fyodor Dostoevsky"),
        SessionQuote(text: "Realists do not fear the results of their study.", author: "Fyodor Dostoevsky"),
        SessionQuote(text: "The formula 'Two and two make five' is not without its attractions.", author: "Fyodor Dostoevsky"),
        SessionQuote(text: "Man only likes to count his troubles, but he does not count his joys.", author: "Fyodor Dostoevsky"),
        SessionQuote(text: "We learn about life not from plusses alone, but from minuses as well.", author: "Anton Chekhov"),
        SessionQuote(text: "Knowledge is of no value unless you put it into practice.", author: "Anton Chekhov"),
        SessionQuote(text: "You must trust and believe in people or life becomes impossible.", author: "Anton Chekhov"),
        SessionQuote(text: "People don't notice whether it's winter or summer when they're happy.", author: "Anton Chekhov"),
        SessionQuote(text: "Love, friendship and respect do not unite people as much as a common hatred for something.", author: "Anton Chekhov"),
        SessionQuote(text: "There is nothing new in art except talent.", author: "Anton Chekhov"),
        SessionQuote(text: "Advertising is the very essence of democracy.", author: "Anton Chekhov"),
        SessionQuote(text: "There is nothing like a dream to create the future.", author: "Victor Hugo"),
        SessionQuote(text: "All the forces in the world are not so powerful as an idea whose time has come.", author: "Victor Hugo"),
        SessionQuote(text: "To love beauty is to see light.", author: "Victor Hugo"),
        SessionQuote(text: "Perseverance, secret of all triumphs.", author: "Victor Hugo"),
        SessionQuote(text: "Life is the flower for which love is the honey.", author: "Victor Hugo"),
        SessionQuote(text: "Change your opinions, keep to your principles; change your leaves, keep intact your roots.", author: "Victor Hugo"),
        SessionQuote(text: "When grace is joined with wrinkles, it is adorable. There is an unspeakable dawn in happy old age.", author: "Victor Hugo"),
        SessionQuote(text: "A thorough knowledge of the Bible is worth more than a college education.", author: "Theodore Roosevelt"),
        SessionQuote(text: "To educate a man in mind and not in morals is to educate a menace to society.", author: "Theodore Roosevelt"),
        SessionQuote(text: "Great thoughts speak only to the thoughtful mind, but great actions speak to all mankind.", author: "Theodore Roosevelt"),
        SessionQuote(text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt"),
        SessionQuote(text: "With self-discipline most anything is possible.", author: "Theodore Roosevelt"),
        SessionQuote(text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt"),
        SessionQuote(text: "Speak softly and carry a big stick; you will go far.", author: "Theodore Roosevelt"),
        SessionQuote(text: "'Beauty is truth, truth beauty,' - that is all ye know on earth, and all ye need to know.", author: "John Keats"),
        SessionQuote(text: "I am certain of nothing but the holiness of the heart's affections, and the truth of imagination.", author: "John Keats"),
        SessionQuote(text: "Scenery is fine - but human nature is finer.", author: "John Keats"),
        SessionQuote(text: "My imagination is a monastery and I am its monk.", author: "John Keats"),
        SessionQuote(text: "A thing of beauty is a joy forever: its loveliness increases; it will never pass into nothingness.", author: "John Keats"),
        SessionQuote(text: "Philosophy will clip an angel's wings.", author: "John Keats"),
        SessionQuote(text: "Nothing ever becomes real till it is experienced.", author: "John Keats"),
        SessionQuote(text: "Some people will never learn anything, for this reason, because they understand everything too soon.", author: "Alexander Pope"),
        SessionQuote(text: "And, after all, what is a lie? 'Tis but the truth in a masquerade.", author: "Alexander Pope"),
        SessionQuote(text: "Hope springs eternal in the human breast: Man never is, but always To be Blest.", author: "Alexander Pope"),
        SessionQuote(text: "How happy is the blameless vestal's lot? The world forgetting, by the world forgot.", author: "Alexander Pope"),
        SessionQuote(text: "A little learning is a dangerous thing; Drink deep, or taste not the Pierian spring.", author: "Alexander Pope"),
        SessionQuote(text: "Many men have been capable of doing a wise thing, more a cunning thing, but very few a generous thing.", author: "Alexander Pope"),
        SessionQuote(text: "To err is human; to forgive, divine.", author: "Alexander Pope"),
        SessionQuote(text: "In seed time learn, in harvest teach, in winter enjoy.", author: "William Blake"),
        SessionQuote(text: "Exuberance is beauty.", author: "William Blake"),
        SessionQuote(text: "Opposition is true friendship.", author: "William Blake"),
        SessionQuote(text: "The true method of knowledge is experiment.", author: "William Blake"),
        SessionQuote(text: "Travelers repose and dream among my leaves.", author: "William Blake"),
        SessionQuote(text: "The bird a nest, the spider a web, man friendship.", author: "William Blake"),
        SessionQuote(text: "Art can never exist without naked beauty displayed.", author: "William Blake"),
        SessionQuote(text: "My dear friend, clear your mind of cant.", author: "Samuel Johnson"),
        SessionQuote(text: "Words are but the signs of ideas.", author: "Samuel Johnson"),
        SessionQuote(text: "Kindness is in our power, even when fondness is not.", author: "Samuel Johnson"),
        SessionQuote(text: "Great works are performed not by strength but by perseverance.", author: "Samuel Johnson"),
        SessionQuote(text: "By seeing London, I have seen as much of life as the world can show.", author: "Samuel Johnson"),
        SessionQuote(text: "Curiosity is one of the most permanent and certain characteristics of a vigorous intellect.", author: "Samuel Johnson"),
        SessionQuote(text: "Integrity without knowledge is weak and useless, and knowledge without integrity is dangerous and dreadful.", author: "Samuel Johnson"),
        SessionQuote(text: "The most certain sign of wisdom is cheerfulness.", author: "Michel de Montaigne"),
        SessionQuote(text: "A wise man never loses anything, if he has himself.", author: "Michel de Montaigne"),
        SessionQuote(text: "Rejoice in the things that are present; all else is beyond thee.", author: "Michel de Montaigne"),
        SessionQuote(text: "Valor is stability, not of legs and arms, but of courage and the soul.", author: "Michel de Montaigne"),
        SessionQuote(text: "Nothing fixes a thing so intensely in the memory as the wish to forget it.", author: "Michel de Montaigne"),
        SessionQuote(text: "There is no passion so contagious as that of fear.", author: "Michel de Montaigne"),
        SessionQuote(text: "Lend yourself to others, but give yourself to yourself.", author: "Michel de Montaigne"),
        SessionQuote(text: "Who questions much, shall learn much, and retain much.", author: "Francis Bacon"),
        SessionQuote(text: "Travel, in the younger sort, is a part of education; in the elder, a part of experience.", author: "Francis Bacon"),
        SessionQuote(text: "Friends are thieves of time.", author: "Francis Bacon"),
        SessionQuote(text: "It is impossible to love and to be wise.", author: "Francis Bacon"),
        SessionQuote(text: "Silence is the sleep that nourishes wisdom.", author: "Francis Bacon"),
        SessionQuote(text: "Hope is a good breakfast, but it is a bad supper.", author: "Francis Bacon"),
        SessionQuote(text: "Beauty itself is but the sensible image of the Infinite.", author: "Francis Bacon"),
        SessionQuote(text: "To every action there is always opposed an equal reaction.", author: "Isaac Newton"),
        SessionQuote(text: "If I have done the public any service, it is due to my patient thought.", author: "Isaac Newton"),
        SessionQuote(text: "We build too many walls and not enough bridges.", author: "Isaac Newton"),
        SessionQuote(text: "Errors are not in the art but in the artificers.", author: "Isaac Newton"),
        SessionQuote(text: "It is the weight, not numbers of experiments that is to be regarded.", author: "Isaac Newton"),
        SessionQuote(text: "I can calculate the motion of heavenly bodies, but not the madness of people.", author: "Isaac Newton"),
        SessionQuote(text: "If I have seen further than others, it is by standing upon the shoulders of giants.", author: "Isaac Newton"),
        SessionQuote(text: "Learning never exhausts the mind.", author: "Leonardo da Vinci"),
        SessionQuote(text: "Why does the eye see a thing more clearly in dreams than the imagination when awake?", author: "Leonardo da Vinci"),
        SessionQuote(text: "A well-spent day brings happy sleep.", author: "Leonardo da Vinci"),
        SessionQuote(text: "Water is the driving force of all nature.", author: "Leonardo da Vinci"),
        SessionQuote(text: "The noblest pleasure is the joy of understanding.", author: "Leonardo da Vinci"),
        SessionQuote(text: "Where there is shouting, there is no true knowledge.", author: "Leonardo da Vinci"),
        SessionQuote(text: "All our knowledge has its origins in our perceptions.", author: "Leonardo da Vinci"),
        SessionQuote(text: "I am still learning.", author: "Michelangelo"),
        SessionQuote(text: "Genius is eternal patience.", author: "Michelangelo"),
        SessionQuote(text: "There is no greater harm than that of time wasted.", author: "Michelangelo"),
        SessionQuote(text: "The true work of art is but a shadow of the divine perfection.", author: "Michelangelo"),
        SessionQuote(text: "The marble not yet carved can hold the form of every thought the greatest artist has.", author: "Michelangelo"),
        SessionQuote(text: "Faith in oneself is the best and safest course.", author: "Michelangelo"),
        SessionQuote(text: "A man paints with his brains and not with his hands.", author: "Michelangelo"),
        SessionQuote(text: "Beauty awakens the soul to act.", author: "Dante Alighieri"),
        SessionQuote(text: "All hope abandon, ye who enter here!", author: "Dante Alighieri"),
        SessionQuote(text: "Remember tonight... for it is the beginning of always.", author: "Dante Alighieri"),
        SessionQuote(text: "Heat cannot be separated from fire, or beauty from The Eternal.", author: "Dante Alighieri"),
        SessionQuote(text: "There is no greater sorrow than to recall happiness in times of misery.", author: "Dante Alighieri"),
        SessionQuote(text: "If the present world go astray, the cause is in you, in you it is to be sought.", author: "Dante Alighieri"),
        SessionQuote(text: "Consider your origins: you were not made to live as brutes, but to follow virtue and knowledge.", author: "Dante Alighieri"),
        SessionQuote(text: "Time passes irrevocably.", author: "Virgil"),
        SessionQuote(text: "Time is flying never to return.", author: "Virgil"),
        SessionQuote(text: "Time flies never to be recalled.", author: "Virgil"),
        SessionQuote(text: "Fear is proof of a degenerate mind.", author: "Virgil"),
        SessionQuote(text: "They succeed, because they think they can.", author: "Virgil"),
        SessionQuote(text: "Endure the present, and watch for better things.", author: "Virgil"),
        SessionQuote(text: "Fate will find a way.", author: "Virgil"),
        SessionQuote(text: "While there's life, there's hope.", author: "Marcus Tullius Cicero"),
        SessionQuote(text: "Love is the attempt to form a friendship inspired by beauty.", author: "Marcus Tullius Cicero"),
        SessionQuote(text: "Friendship improves happiness and abates misery, by the doubling of our joy and the dividing of our grief.", author: "Marcus Tullius Cicero"),
        SessionQuote(text: "A friend is, as it were, a second self.", author: "Marcus Tullius Cicero"),
        SessionQuote(text: "A man of courage is also full of faith.", author: "Marcus Tullius Cicero"),
        SessionQuote(text: "Cultivation to the mind is as necessary as food to the body.", author: "Marcus Tullius Cicero"),
        SessionQuote(text: "The more laws, the less justice.", author: "Marcus Tullius Cicero"),
        SessionQuote(text: "What we achieve inwardly will change outer reality.", author: "Plutarch"),
        SessionQuote(text: "The mind is not a vessel to be filled but a fire to be kindled.", author: "Plutarch"),
        SessionQuote(text: "Do not speak of your happiness to one less fortunate than yourself.", author: "Plutarch"),
        SessionQuote(text: "Silence at the proper season is wisdom, and better than any speech.", author: "Plutarch"),
        SessionQuote(text: "The very spring and root of honesty and virtue lie in good education.", author: "Plutarch"),
        SessionQuote(text: "Courage consists not in hazarding without fear; but being resolutely minded in a just cause.", author: "Plutarch"),
        SessionQuote(text: "Medicine to produce health must examine disease; and music, to create harmony must investigate discord.", author: "Plutarch"),
    ]

    static func random() -> SessionQuote {
        all.randomElement() ?? SessionQuote(text: "Wisdom begins in wonder.", author: "Socrates")
    }
}
